settings:
    index:
        # single node, no sharding
        number_of_shards: 1
        number_of_replicas: 0


mappings: 
     
    properties: 
        title: 
            type: "text"
            analyzer: "english"
        summary:
            type: "text"  
            analyzer: "english"          
                
        author:
            type: "text"
            analyzer: "english"

        content: 
           type: "text"
           analyzer: "english"    
        
    
      

    
               